### ISSUE TITLE
Is there any technical paper or document about your moire pattern simulator?

### ISSUE THREAD

**Issue by leaderkent** [mr3coi/screen_photo_simulator#16]
your moire pattern simulator is really cool! But I want to know more detail about it. Is there any paper or document can help me learn about it?

**Comment by mr3coi** [comment]
Unfortunately, as far as I know there wasn't much prior research done on this topic (simulating moire patterns in a differentiable manner) and so I've just implemented it off the top of my head although I did have some idea of what was happening optically.

Thanks for the interest, though.
